export class UserInfoModel {
  id?: number
  username?: string
  nickname?: string
  mobile?: string
  email?: string
  avatar?: string
  gender?: number
  score?: number
  token?: string
  user_id?: number
  createtime?: number
  createTime?: string
  expiretime?: number
  expires_in?: number
  bio?: string
  download_num?: number
  birthday?: string
  prevtime?: number
  prevTime?: string
  logintime?: number
  loginTime?: string
  loginip?: string
  loginfailure?: number
  joinip?: string
  jointime?: number
  joinTime?: string
}